// Code generated by "stringer -type=Flag -linecomment"; DO NOT EDIT.

package flag

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[String-0]
	_ = x[Required-2]
	_ = x[Array-4]
	_ = x[Int-8]
	_ = x[Int64-16]
	_ = x[Uint-32]
	_ = x[Uint64-64]
	_ = x[Float64-128]
	_ = x[Bool-256]
	_ = x[Duration-512]
	_ = x[Time-1024]
	_ = x[Any-2048]
}

const _Flag_name = "stringrequiredarrayintint64uintuint64float64booldurationtimeany"

var _Flag_map = map[Flag]string{
	0:    _Flag_name[0:6],
	2:    _Flag_name[6:14],
	4:    _Flag_name[14:19],
	8:    _Flag_name[19:22],
	16:   _Flag_name[22:27],
	32:   _Flag_name[27:31],
	64:   _Flag_name[31:37],
	128:  _Flag_name[37:44],
	256:  _Flag_name[44:48],
	512:  _Flag_name[48:56],
	1024: _Flag_name[56:60],
	2048: _Flag_name[60:63],
}

func (i Flag) String() string {
	if str, ok := _Flag_map[i]; ok {
		return str
	}
	return "Flag(" + strconv.FormatInt(int64(i), 10) + ")"
}
