// Code generated by "stringer -type=Flag -linecomment"; DO NOT EDIT.

package input

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ValueString-0]
	_ = x[ValueRequired-2]
	_ = x[ValueArray-4]
	_ = x[ValueInt-8]
	_ = x[ValueInt64-16]
	_ = x[ValueUint-32]
	_ = x[ValueUint64-64]
	_ = x[ValueFloat64-128]
	_ = x[ValueBool-256]
	_ = x[ValueDuration-512]
	_ = x[ValueTime-1024]
	_ = x[ValueAny-2048]
}

const _Flag_name = "stringrequiredarrayintint64uintuint64float64booldurationtimeany"

var _Flag_map = map[Flag]string{
	0:    _Flag_name[0:6],
	2:    _Flag_name[6:14],
	4:    _Flag_name[14:19],
	8:    _Flag_name[19:22],
	16:   _Flag_name[22:27],
	32:   _Flag_name[27:31],
	64:   _Flag_name[31:37],
	128:  _Flag_name[37:44],
	256:  _Flag_name[44:48],
	512:  _Flag_name[48:56],
	1024: _Flag_name[56:60],
	2048: _Flag_name[60:63],
}

func (i Flag) String() string {
	if str, ok := _Flag_map[i]; ok {
		return str
	}
	return "Flag(" + strconv.FormatInt(int64(i), 10) + ")"
}
