kind: pipeline
name: default

steps:
- name: golangci-lint
  image: golangci/golangci-lint:v1.49
  volumes:
    - name: deps
      path: /go/src/mod
  commands:
  - golangci-lint run --timeout 5m

- name: test 
  image: golang
  volumes:
  - name: deps
    path: /go/src/mod
  commands:
  - go test ./...

- name: example golangci-lint
  image: golangci/golangci-lint:v1.49
  volumes:
    - name: deps
      path: /go/src/mod
  commands:
  - cd example
  - golangci-lint run --timeout 5m

- name: example test
  image: golang
  volumes:
  - name: deps
    path: /go/src/mod
  commands:
  - cd example
  - go test ./...

volumes:
- name: deps
  temp: {}

