version: "2"
linters:
  default: all
  disable:
    - exhaustruct
    - gomoddirectives
    - ireturn
    - wsl
    - noinlineerr
    - depguard
  settings:
    funcorder:
      constructor: false
    dupl:
      threshold: 100
    funlen:
      lines: 100
      statements: 50
    goconst:
      min-len: 2
      min-occurrences: 2
    gocyclo:
      min-complexity: 15
    lll:
      line-length: 140
    misspell:
      locale: US
    staticcheck:
      checks:
        - all
        - -SA1030
    varnamelen:
      min-name-length: 2
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - mnd
          - varnamelen
        path: _test\.go
      - linters:
          - dupl
        path: input/variable
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
