linters-settings:
    dupl:
      threshold: 100
    funlen:
      lines: 100
      statements: 50
    goconst:
      min-len: 2
      min-occurrences: 2
    gocyclo:
      min-complexity: 15
    golint:
      min-confidence: 0
    gomnd:
      settings:
        mnd:
          # don't include the "operation" and "assign"
          checks: argument,case,condition,return
          ignored-functions:
            - "strconv.*"
            - "strings.*"
    govet:
      check-shadowing: true
    lll:
      line-length: 140
    maligned:
      suggest-new: true
    misspell:
      locale: US  
    varnamelen:
      min-name-length: 2
    staticcheck:
      checks: ["all","-SA1030"]

linters:
    enable-all: true
    disable:
      - varcheck
      - maligned
      - scopelint
      - nosnakecase
      - ifshort
      - golint
      - interfacer
      - structcheck
      - deadcode
      - exhaustivestruct

      - ireturn
      - exhaustruct
      - gomoddirectives

issues:
  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    - path: _test\.go
      linters:
        - gomnd
        - varnamelen
    - path: input/variable
      linters:
        - dupl
