// Code generated by "stringer -type=Verbosity -linecomment"; DO NOT EDIT.

package verbosity

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Quiet - -1]
	_ = x[Norm-0]
	_ = x[Info-1]
	_ = x[Debug-2]
	_ = x[Trace-3]
}

const _Verbosity_name = "quietnorminfodebugtrace"

var _Verbosity_index = [...]uint8{0, 5, 9, 13, 18, 23}

func (i Verbosity) String() string {
	i -= -1
	if i < 0 || i >= Verbosity(len(_Verbosity_index)-1) {
		return "Verbosity(" + strconv.FormatInt(int64(i+-1), 10) + ")"
	}
	return _Verbosity_name[_Verbosity_index[i]:_Verbosity_index[i+1]]
}
