// Code generated by "stringer -type=ArgType -linecomment"; DO NOT EDIT.

package variable

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TypeOption-1]
	_ = x[TypeArgument-2]
}

const _ArgType_name = "optionargument"

var _ArgType_index = [...]uint8{0, 6, 14}

func (i ArgType) String() string {
	i -= 1
	if i < 0 || i >= ArgType(len(_ArgType_index)-1) {
		return "ArgType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _ArgType_name[_ArgType_index[i]:_ArgType_index[i+1]]
}
